server:
  port: 8091

spring:
  application:
    name: balance-tracker-api

msa:
  auditsystem:
    transaction:
      limit: 1000 # Max Transaction Limit to submit to the Audit System.
      maxAmountPerBatch: 1000000 # Max absolute amount per batch in £.